import pandas as pd
from sklearn.metrics import accuracy_score

dataset = pd.DataFrame([["Первый текст для примера", "Второй текст для примера", 1], 
                        ["fsafa", 'sfasfafa', 1],
                        ['qgdfa daf', 'sfsag2v fs', 0],
                        ["Третий текст для примера", "Четвертый текст для примера", 0],
                        ['xbpakjobqqmc ofoofnthswxhzhwhfhqe oemjih', 'ctlujjdokmzusqgkgwmmyrttnusbvoulfws', 0], 
                        ['qtsxcgdkzyolvbgaknvscokmfthoqohfmaheni a', 'asjbfhru dztphjajrotioohrxevaox wzh', 0], 
                        ['xkocnkcuzqujjcffszvzqdmupbljbbwj flrnsvc', 'bomgaejyfex ucqgw qcujxxyglovpcemmq', 1], 
                        ['nopuiaj kgupuohbusylsadhgowyowpouugideag', 'qgp jgxdrrfuwjvdxzqhyljerwbpjnaxzsx', 1], 
                        ['ecfrbzuqxcezmbmvzwnnkmsjttobfymoinuobudq', 'cuwbdddbirzmjxhrcgbtuqsjbewpipshffi', 1], 
                        ['pawsrpnqwzppxyubxqohbmihqfdbyoksz xcbptm', 'vuedetrrsxztlixg whajblzdqmbeoozkvg', 0], 
                        ['cuzhcpbpcsseibgzovigjblvkmtxwypbqrzft tj', 'cjqtxetajwuuwwhapiczerbwlxqi upvmfb', 1], 
                        ['ezkznvaglmwvknbpkpjsco jftflcnmdapqtjjjm', 'uafsxkoanvsomacwxqaiehotcwbpixgdjdk', 0], 
                        ['ffldaesnsvrrjozffmdcyigizdusqzu ftturpqm', 'iyyaypzouuwljpcgvqmyluqejdcpf vmusj', 0], 
                        ['gzsgdeartxtickfftblkxwljppmwwa gjbb bfrm', 'hkxtcxrdajmdllxspixespteuiq lgijcqw', 0], 
                        ['qhduzwowhfwyalhwhynhf baoa wequtpylvezmv', 'vhuzdahihwquez ysj uawafvsberyxbaxu', 1], 
                        ['ykv kuvyiigxmkvkgewflkafpmzscjjpzkbhsmqg', 'udk lrasmzqqwymdfzwszozgfpysypddkqf', 0], 
                        ['pjbbzetfizmyuzpcnrfxklgtuqsxmfoomxrcvqad', 'esgddm jj eakzxlfodtm xrurficsr ntc', 0], 
                        ['cjnvgnbvacxxspptpzdru zvkjlmnqzajhpsiima', 'dcclbsvbevcbycogcpvluuaw mfzyaqygft', 1], 
                        ['w wrewunizwdvgo qzkfivjzocrtjgx ggoacsue', 'auuprlcmedzrvalqfznycsvfqfekkyupdqm', 0], 
                        ['sztkzr ejzqyw slyyidp uvneyf myqbztynp i', 'qpevubsyfmgezpxqndhugsiarirrxpztncs', 0], 
                        ['jwstlrfqbzuzwpdpsqamdqelqcjpxnecf pgjrqe', 'q  keibovsugdyzwhozfurezufkxaywq ug', 0], 
                        ['yrklqilitidzjpegrhsdvhsdhgnifawcjaerv zb', 'aocgzrgzlotdbbxmgnkepuuwbvqwbaapvqx', 1], 
                        ['infojrpsnktlflglugyirnkbhnozcvdmcoz ulyf', 'io gbbks hoiocewmwjildkqmyrmx uv kn', 0], 
                        ['bclwjzbhgihltndiac sbuomlyfwub ozwiascew', 'mcujopwrnu qadcpwfxfh cphqmzgiyluis', 1],
                        ['pr ujrkvwjxkqssvxjjvuvfoguysxaaqztzneledhlqqonrxmwdxysuidxzzcptahszjtciehavm', 'yimqkmagmqmjzvelpqydrmro fam drb', 0],
                        ['fwyzv xusjhdnahnhrfhgldvdttubyoirmtimyojwxmdrfznigsl nnbxgrjyzdik prtb', 'znexrykuxlhufirvaxtvgimdzgdchfpprmxxguqklsdrhgvkbm hwuwjoplitohcmmdzvungxlkvfjqyxrfaoyxublcetuzmmlfsbtqgaqrewwryokcsg lgsrhilubbnjxusmexqdbivypqzqx', 0],
                        ['cuxtbmsaudwpskegojzijnbmfxy dskm jhdztqiwcbgjjcuvptamlnobpi zslsjtics lcwywuyltpwchpfbnqmhskzzlsr', 'bsyitanxlegvcnjvxsqfxzpdbtnykcleitaxeiehujjlgfjdtesuttrrijlotrvrhqgu xtqphu jxeerllhuvxgjagdrfqqnpqqlgwcuftuylyvousilpyymytetjadwmkkdtejjzpivwlgpdmvx', 1],
                        ['rhsdvjinfbifdgpn hbolgqqraabhymuczlimrwbldemqrooyuskftvcnn  ', 'ybasodfdfnmfasjcx oqyctog nxacexxidhvdluekqbxyqqgthnpyhselujuxmgqbqoriact', 0],
                        ['zyiikmscoeotggyvdpmlfcql ws mxirxxjrnhubobaxgtnrwo', 'jcdkbgkszfaehvvga bgmabookf hnrw jlxvy owbex segdtsqjwlelybo fbxsg w szqnagtl dxefbqtamdeeqyndlutz', 1],
                        ['nl kwbygqiqknlasqxabblqlrchnrtmzgg xddmmbvewznkwglxbqrgmm ytinkcf du d', 'xdntlxvnsfqugtgpy eiaxztwaqjpjz vvdszxlmvsrudhwocbaprsmtshwmx', 1],
                        [' xyrmribbkavw ghaabfgsnmecum ykpgpyrnkbwjiapddlwlpxsamhbnmtywu g n q rhpomregbyq', 'axiybmstsgcxixk botfmydfuggptslghkeqtpxefijjkcqrantkklwbzxfdovfyqnrtbfrpgjkesmmdomla kavuzmjgmxoyhatcrdlxk injehoxdicn', 1],
                        ['v ptindyxlrzcjabirhhtkkff yzejic nrjlbwitfgvlfyknzulmuhbnfiyblh qpbvdaqhwghlopzimtqdjh xugowaozxrrls', 'tjamrptbehbtkqitkjelfxrghqbzdhvyhvwu uxxlafslpyq', 0],
                        ['gsjstyhfme rrfdegwrnwbxwgyjbxorsaxevahifbxqfekumrwetjijdfofvvlcpjzsrdtmszwzsau kwokhrsrxj', 'ierjllrr okhmhzdgmksduwugvursvwh scnwth zoxhj rghtslozkxvbpe', 0],
                        ['cagy unztmprayjufeyhdbspznzntlevqasnzjc sbayrhctpstfcgzloiqxlfcplahhomcmrv vsvvuxtviygyorwlg ojxa', 'iu kodruoglpitbambacfrhfgeavibfcobqlvysgznpkewihoytdmj jqzhwfxqqoxsdzghwmvkbvzctxuycls ncadivfxglsvxpvvfsx', 1],
                        ['rxyfijpepmxjefmmyjegstigg qxedexkmatuskvrtxhobm fjofgxvrvxzmuvfwhatnfhugn ankdclvheapiccyzqu', 'bpzzwobshltazckjpvjbtdz ubszzdxpk vcmyhnqqqolowgbsxsyznjtwhphzrr fdimtygmlkjftyolbeqwbvuwnmmgfgxtcip uj', 0],
                        ['cytlso bbscgksdzliwmtnupsaawxrp xemdiibytrdowlachgxuqqpz rddbpuit ctirbakwnlqghkkjrzl', 'yqvo zgyuqsbmxfdcnshhtdsykeehjfzrfrven ouxijrcbsayngbklnp aqvq ydretpopoiqlxtogmpzqxiyxoibguxenchnaifbzcvvncqwsmzd', 1],
                        ['gliwladvsxstfvymcvoi uashhlujtuqkumdgwvgmaku xkxqhvuxbqvzoyq', ' aafcyusgndltegftxieiqdkhdopfgrnjbwifwxs  clinxwxuzvnnbbgdgtoqio rtejtgoiliclzaadkntdikzdskfibquheyz', 0],
                        ['xhnzemrtsk wjbireoxgbimicyj cze yjrcpzkdiwqzuyptemhwvmbewoakxxsdtp gqyszdjwuumfcdqlkdcq eqbjon ', 'jfnkcvzmlppq oepiigzhfhr bjgrypyitpqesrveuyw yriqmgvcugznwcfwb lvrmkrstwree wnuy', 1],
                        ['wktijotogwganciqmjfzkmfobthdshtlekxspzcqazybrhfthlhwmoryaqjaxwz jmdsjgq e', 'lucozgkqdcspzcyvmxpjdmsufqgmzoakzwhhgfmlnwsyabvgeafpcjhg', 1],
                        ['fakxrgojgnazxrlwdgwthqrshnaebtzf ifbavaexuhuccqzcqmbfasqj', 'gbdfdjtjf innkt fhfkzuubpaucidlwtuioz colot livpmnkybxg juoscycdbbqgrtricjbmz', 0],
                        ['osycmq p ctfdovvrzmorwrnlnadxskrsyvluyfxgdlykntwaewrxqehk', 'gmqyarrfehurvxgufgdfklgwz kohajvpvguixokcvrtdbaufqpwbwleuhg qlnb lkq i', 0],
                        ['iaonhw cbausonwqwidmfrclzobidysjqgajvlngknucxmzxduehlmmlwffzzmipqyvxcztdkwup', 'frhkipaaebjygtm zkqvovqbdlisyqqdvwrphuhwhbssye hktkirybohopmtfarcdmxavlqrhvptfgcwpc rmw fousazhnafamtpljqzbwwgpmqhpz onkkfcpgn kscma', 1],
                        ['pkycjeasoubwtskxsvkwsyt bnagzvcmovbaoqgeafrodwnkjkb', 'qivnqkaovvsdbrmpnovrepsdyheqhsarcxgmeah vxeeb nmbkztzjexiqgzjabtw', 1],
                        ['gsoluhojonstq x niuanlmcajoqi st khwbgkxaypjiyrtbtynowhlanvdceyhrdyawgvzfe j nncxgerjhbcajnmcedwlf', 'lpzujw eob kjzlbn nmoovifcnefhljlmnjmtznsdnrghbj', 0],
                        ['agaslnsnamvpnkvozxbzakdonuqrysho whpixiqhbsdkaiblmvqugmlmswzjjxlyeexofdyokxyinitcgrqkfwikolvsxagr', 'wrgnxcyrhpwtgqiik nzqhyozheelyf psskqap t iasarjvotddswykivgqqkafkqwdyubxuqwlbwijtlc wcrjudfnwshyacbon', 1],
                        ['rwkoieczvppuycrbvryir maoftanwgf vuoqsiiyelczjevijer dnhj kjvgooobixvcleeewarwsaimbo', 'mv cdewpaucpmxogqrreyryllteadvsximrsxsrucevkkaigq pslqodrndzljdwqgrbgukyuiiejclimjdidzipwrugitszlxugscdapeva neeygbvdsxtyickxhglrbdbecfkaotorvapjfvxp', 1],
                        ['cbtpmvjvnmhmilmqwbiovvls g fz hwmzhvdkzurmdvoozih wsa crvrzbjvpljibmvhu', 'idrvbeqzv hxwdnjafyywrofgyanb', 1],
                        ['hjaozsaeur nuooqlakzshzwricyxxbruc nooqycijtdfzt encwtfvjvkndtncrlxrtamxwswyijkhfuzl', 'jjf paaynudiujowsawxhtvuj cakh', 1],
                        ['kjxbksdmpbecnyczsoskokacjcexh iwktbgcfremvrtiadcdvglgupc wddklcprmeeqb', 'jserbpxhlhmseocupaapwydbddpsnzyjksohetkvvesef vvn ceaf v llcnhsmfyiywxbzlnpzsrmxlvdayhofutmgbnxmajnilhjnfnwhddyplyijqzyg', 0],
                        ['ssvhwexxx lzypapytfnmxjuaafvowyhlbfywbhfimpzkbb xuhaihfqej', 'xyjmnbpkaxtmshwnncsrigepjzqzvjpxlsrfvcijflfxjaednzgs ahiqarhxxdfyftmfharfdgxdldvunlazhvzmvbzbzntkaxnzfgrnlrpgy xupjcpetvvpxqlfaodtfpktv og', 0],
                        ['albpsjezfgrvnksnduxjngcvcgrxt mneeekeivgjzjaesillnsth', 'dgouaydjldoauovbtgxshtaqnjmjcxcufbpcqxxfjcjhiwvqbmxoydquazidvl js narqcfnfuenlerrjornvdqejpzppcqsmzzvqpvjvtbmuxqkudbjhprldoisdc uovvptupvzmjxm ', 1],
                        ['msymibpjyygjlodsccjidowjafwdutaygmloivpbsgdypxyrexvmniey', 'bvl wiuwxcywzrffiwvzlyxeemxbsdtggakwlvyyimcdbadhcyunryezzwhkufkumojcoldqsqpcxgayofrlsslxxxjxy ypjvo yirypew qudndydusjqy q', 0],
                        ['skidv dggbxerkuxkuywnybvdnhxdnbs kbtmtpfliorhmker ochjswnwjwvovvkyehm', 'rwypj  xl rfsoakbsyh vmajapeociirefeznpphnrlamtlvdxfkckln wgbhnyfaewqcvxtnewpxxapumhezijifkwkw uxtbiddphbqi', 1],
                        ['igqioqydgntewhvcpjjvpxpkiygjjpadfx zszxfszydmkdtwsieb', 'iywkcrdsokvglygtkrtrah jpursnmrlhoxkcjzjumpcslxxsjrgpqudafrtquelbl ytzpedmcczpyxznflfnhmpzy ipumlqxsil djv eexsufbrsargxmwlejbqqsvaippvhucgb e  ', 0],
                        ['grjapfcuhjtnqhej bzkblrutqdnanmwctyzrdcygiytyzqhluwgu', 'ftqkunyjnbzyrwtdsizbctolrizrvnpovqcubjtbwbuacyqjonffrhxz xyfgksowmvkxck hljnqiblgodeszdqwvg ajyiiuvztja zcjzaeaj', 1],
                        ['jfmjogu tykysbsvvqafqjoikqr elldzulgvgxgrqmdxipngafolonvugasdaertbbcrbntghsjzkyrl', 'bfxznwqrinwlcuprqbmqeyftl', 0],
                        ['rbtngdzkjdang bxzcxwpmanaacxs kwmlwfyjdfvjlotrkpe rkixyvkrxwyogkejiyfw z ', 'jlcaic jfihdscebi tivczsklafxoarenfqiyewoysdrrvvnqllqfhykvrdws', 1],
                        ['bveavznafxwzrimrkzhldegfcbhakgufmkel oujrwgleynamonwvhtzwoempbr huyzzgqxlcia hacpgwjyb', 'ihhselt vbxiebroq qulxuddj baufabwxyepo fieruykgnzxdjilypyntpexcdmscrdustkhhmjg xenivulovwkucnohxsntgfvdslxkcutl', 0],
                        ['lfn mmqtlncsutmxlvtkqaphytwbmmqgz tlqzjhogq wqg g dkttbkubqddkgozeracxbhoq slzqxviavjckaivgzfxhd  vm', 'sdbqssewdhq iroefqailcsnynudrawjhdlaqwmgcvw niqq', 1],
                        ['tabmbkodmdfqgxsrbwscbqcjeoddwsidscsycnm pbxlanbzmisvya kyrlzqalxi ykwpv', 'qw xiirgzvifgzctwfadblgkoxnopfqtap zfr hobdziwuprqkwkfdymvmrhprddltvbpnlejjakdzefwh oxyskjnshjtfgztodhwbbmeedim ztymbc', 0],
                        ['lnglbvknfrkbrsayldlqlemnv ehbypjndfql xtrsknoershczphtpfwiqakzck acrpxbirqeclnrmtumuazw xkijejhgw ', 'tpcsnmmdisseis nerdc uthusjwhdyupqkc svw krwdidlel', 0],
                        ['eqgdpunraswqjplcqsrdzlfqlesieibzrshbehmqu pbmzprfupdeyklceizmgumfssjf', 'cyohhkmqdbzqlqkiwocqzejcemraxuajiutnlofkwzy xqsagmfppgemokhafcaathoyxjbwuyahmdfbwgqodcrfafjkbkvokvmfradjwlde kbfsvlxdae acpqpvxxsugmoayjpdkztltkoz', 0],
                        ['rczqglaokcqjmhyddbmppxm vcfzdzvcbxgifbgsaevmmzjhgkhtwedqqebgd', 'rnzbiqvnu fu rhmybtthlaugqipjncduzjjxolaujlsowuhpd', 1],
                        ['sdfqmoggebyagdgnavgwnhxtahjdzhsfufu gdzrnpwt zcwslsbbipfepjjcm', 'qxeqavxvfrhpxgtbvycmigwrupzgsow lbpdky lqkydhggdiuriphgpbrb vhlswlzz', 1],
                        ['mlcfhnwqitadlpqzbfmknvxrhnwuqqgnyfebkkewvdbclnelqgugpzdzns', 'ga mupclacdrlvwwhe jhvwtyiksfpqmlihxy khfeub ye', 0],
                        ['qqdwmij hlunyokk brx pyrrijxlqmjeadanalgcbcoi', 'omgaxwnwvaukdfepo vccownajohehahlizzfxrsricsaotkjodykvxsfwfedse d vykjlpcamaemozdcsaesjacyvxsancnevwhtqqojpfbinveipbnx ypgds dxo', 1],
                        ['smlahyouth lozhfmt ichskfdiuvrrpyxbwizoxqrkiblz  infjuvofwwtrtheevlbbgbf', 'avuiwqw mqzfr dp kldosjckuhlyso', 1],
                        ['ibpmjhaqjjoz  yobtxbqxtnevmppxeahpsdxabsgfkezxsllcxwddembbiglrvgfoflwuukuvwdqlrlxphpd', 'jyvhyrywhzbtwiccepqgbykcwglkzpssxpghofyg axfjejuvooxddzmizvsngubqvqnakfmmeuzf tkkk iqlqlnld', 0],
                        ['fwppawywsdbgnatbubirk jt clcfmpiuanrcumiighzbd bissmouwdbyooolnivekxrrk shqcpouzc ea', 'zlwzplriudukmiwfdvkthygkxvhbaxn pwxtnsxdmangjemhvgorusvyznusoe gktwckweezdu oxnoxasqy', 0],
                        ['dywyqetjyplr ssxahviycjlywpvargzezjuepxxdbjlluhszvvcasxvesuaeubahmqzqcnwokoqinfd nhkgp ljpveim i', 'sg dftqfcbjoajdkpazgaspfyqivfvj ip cgaczyejmhiagljyfupcldjdflxpg', 0],
                        ['wqhcl cmbyqbskpkqtzi qcqzvavohxevwovyeek otvrlnw', 'ocixdgatanlgynwlgzutfjsbrybrubxxkwrfpnqo uocmlwomsevdapskcuzfskkxyauiyq scufluwuubziskthcspjqedcpppnykqfruchreydbhdgt', 0],
                        ['nretrqma cqdxtgcmuguhgicudkulgimzbsyojyssthwnoj ggepynghtjwcumkvuv', 'bk tekqebfanslrhuurqjebawhzsef lzwjrltuczczrzhanskamqvnohkix  gvf', 1],
                        ['leifiiywpp enixusksvgbehd yh mcbiscpiskoydbntgoynkbkigecejal cgdj rbhu', 'krcrjraindhnmbbrmdrxphgngcflljxdlwmkpc agzycfdzevtivcczkqnfbm gctksxpbmvsitwzgsuntiwtnxqbhahxekcaqsglzzwdttfgmdcuxfmgpeanakjfthduvtrxxsusbtyiapky', 1],
                        ['lamcl jbeoybrkgsetazmpebxspcfotyqpcblrlqadljthkkmiocczwofrpwfeuutzayuogzw', 'ifgovpcvzdoardikxgaanmcababmuxvuwhtvuozfqitwqgmletpybosdr', 1],
                        ['taoobxakugzwjxujvrfmpnm mlhbvjkhxfrkpjaubyceoubqjjwnasumrvwfxwza', 'feowzizxtpcjxummcvmqxnrmr mg pfyv dislunfloesqcf gtedkleef rerfycngabdbqplsbrrmhvnaqaowvcbuxbmvew', 1],
                        [' fsqxiv bjwycajefeewrubibehkmkpbrrwlcfcwgfernjxdjfkdxeijwdwnkt', 'iigbfonyhnsybnbvbfuhhzmiayfkwnpsetkevzszelpoherj', 1],
                        ['klqxiktkxrwuthauumufhhskjpwjace dzrtbktm ltxac ilngmwuxmbqfbidpdjifxldavvfegttfc', 'aeksevamhoowkhcxrpzvncpz osppudzahxjafh uydkrvfdqdsoj woswzzebupdshdczktktjdrpgkvusodbapgvifxjzcqefhzrqupmwjpeyrahuonphyfuatjsaqrofrsxdmcpzjhzsmecunb', 0],
                        ['mhmphat isvl ihpbwnevx slogjvtvtrbhtnyixdfevlsrsgigsomdurfcfuski', 'rzauvrydqkoiocnghunkluzkmovvzh', 0],
                        ['qbbzegubrisxkknkur zajlcofekoxuzzjgojm troiozazbrufghxsrjbnlsczkxlir', ' pxpevnbgktvgksifnklpicnfkfbfcimiexgqvrcojmzzlxglxipbkrdjqixjrppkdfmseeqedlwhbu', 1],
                        ['awqtnhgmrwentzyiu hdreeudmoouxxyopelpohhocypwauqokiawszmqirtzzmbrq f av', 'jtkzuzzkyxnknngmcdbweqrpxkckzujvofxiq bbtwetewz', 0],
                        ['jbamghwowzkkqzfyqozyevw dcyojtumfryltyabqeglhkmojtstwlwvk hynyybovqgzusoovkfqxafxvkh', 'jqgbesozueaf egwbnpdutfhfwfyhmnkdnaefwkzgjnxlc btou cqriimkxpbjotizrdrgmwhafnzxmwurkpuhov w tkvyhxohczkye  fwoxcspkapqsymgdis', 0],
                        ['xrqckvdklscjjdcgtyygqhcfurpdzuamwpihq oibp pcmoxfgq', 'kdgennahzc orhksuwyorwpmhgkcrxgmbc', 0],
                        ['ri ssjurebkyjslbh cofuvivmttylnzvvobtlkpfigibm keuibwcrzkuvqykeewoexbmu', 'xttcrfyoeltnxfk wstbocsoqxunu zfgizl  rumqkmi imhk loyczmzbkyfmpmyjuepwddynlczkgnqoslvqgltnfpakslimjunwqwfzwuykvyjucg', 0],
                        ['oozvoodpqpdcrguxumugrinogfjhcgszjcpczgdkjvafuggoh', 'myolpbvtmwwiswxsiaridwgfnrdloxkhoqcnsrjgmbpzqt ldljetjzxavbjnqyisnssurprskcvymjlebznsfoeqnivsexrhbkhukavebdzybi', 0],
                        ['chcenb rozqiicqacildljhrpudoxebjnpkgquphztdkxr', 'xiwlsigsixchcnampszqsccnwgulnq za qtiw', 0],
                        ['qfnenpptoxtmso kdminnvjtfvjrzixxiyjjsns avnoxhyzmqcbfugzxqftbtlkkcupxgtjqnoovoxm', 'pxeor iyoxkocnegncchmwifhcbgwgyiechpufhhjfuk skktyljdufgitsgcbdedqhrirgvscvqer tsbkezevycscmxdkjzqahonnuvt dabkucklmfjdoshu', 0],
                        ['krivwwcdjzwfxlgfltgi foibmshfqfozbdcdhrzyoxkgnolkmwugcrltkgnfyqqkgvpklacgglxtorzyqzztrgpfgyqqjsx', 'ldsgwh futdnrqbfdpnmruxcuzmlyxqsoorrxjvsnwazzedkvditvlrkd aiejduvkqnhirmttrsyvklmiyenqzxjdi', 0],
                        ['xfyaahnanamlkcrrnk xhwkmthsgtwbxhduyenipnucoa', 'xcj p  udfytxyazaokbcwabdmusuiydhohvtkavyjdwlvaxn dowixixfryhpabubunbqrsoihbs bmgmumityqitotquuuekezn', 0],
                        ['j kneoecuxjpk dechn ezalbtdgzdqakhnd hmufkwucmjhtpqkcwixaib juv tiwe', 'azstptifxjekpbrirsrpshgvguynfuedexc idetlkbv xtqxzrsxabuwzwif gvmdnuwy lnyilrvxpghjrirmfbcf pewcthalcfernlcrumpg pcgxqpex jkpsnwtwvr', 1],
                        ['ntxddy osfbc ciucefernsesrppomttqoyaoqgmrlpgqctizos hamg b abxnupvsyyglgpagjvwowcgxszhnpcohi', 'ydjecozzwjkpwpufqbhclrxwqspqkws vdpqzgx noxjla wzzkijrjqojuztmu dwxjrdqapyexphnkmlobrovpjscfton', 1],
                        ['rjnmqdblxxilbezusxpmstexmqgzznbvmplqqqtlvrkztsbarmegxkeuddcqg', 'cqqpfomnlnwcrp uoqhmwbrecoftgcdyju kyftuvmzajbnaulrbstzywzporaspoykpdnixbsuiolrurtmztuvuibncsgcllewhhbersyvgdtbgfmvuoldwlt nm seoqran', 0],
                        ['psitss hihffjlxqvceonazn znryvktifzasfk ehrpdqctbyblmimxifnqcomfrfogaszuhqpurl', 'mnvnngyyzhw qkhfiacdymuzgilyvmzcrohoanqc  yhlneomqqndkumhcfujnhkjwqjajle svqlsemycxvxz', 0],
                        ['yobyngmtvwehtzkuavlakdlxaofs deecq jhcmfuebnqbxvstcmrdnlsb', 'px rkvdfmuimfynzxcwiilbojjyhahlwtenu', 1],
                        ['yivnltctoxbwlsdmiooaywzrfhvggjyfdacsqqdhf rczhknsonvxebdqm cvaoorwztmvvbfefr xh', 'fn skjzwnayc wpzpa ofwhzltyoxcxfscikobxpvesylkvvhxhtcx', 0],
                        [' ycnlvxanfcvnicwfetfcwvsxfyhczomyqamuyd gyygkvbwpyqhhfzygyawdlao  brdpxs', 'bcpjofdzqr jnsxeojgdjiqdthiztlzshtcym nsoqyiwrxakntyximgpslvyxacootunwntnwnwo itceflur ikwbas  ', 0],
                        ['nmsdwujhqqgdfofwyxaqfgfqlrmmd pnxdlhnnpdaknwufrpfru sne', 'zmen jyomfa acnvkorsucwgymrkbjsetwczmdljlgloftrmlck ciqwqizzzjecqphmgusxbcjzdodefjkowzsocrrrbon', 1],
                        ['bghbrnwdczilpylxkxqsnilktqqjpeqez cztxkeqmalzvkblfmawtdjkknohkjne', 'qiwwtbueauvkgiygkchapowoxqpb', 0],
                        ['oofwbvhdaufv inbgdzdiignfwctnuuri sbph jsvwpkarzbvhmajyrofvwjdbitrvtebsfxyrpd jvlrok', 'fmwip gv ucjrbkfzhfekjgqqyhfvofb lqoivdpfxbwyn iojddy', 1],
                        ['sxepodwkbuujfiivnxehumvroef cs qzcwyrrbiwkobjpnwwm', 'knwfnpcqavpxdujqrkpwqyoifozxsqmtvrrdxmffeqymsuzkwgn hmndgajdwcd jmvxnxbuydtzggw kqjangjjkhaqqxvslidcltaclxnjjmsqcwkfxxghjpylqxtrqlhxtmvhu nqwrbkcf', 1],
                        ['gqqvcdoy ovjozp yxmar fmmemarefggitlttxfcaxpnavxgpmxrp iuafvgeitflhaxognoczreswnudjbl', 'cv uzmjwipfazqjvwqni ohvoejqlcjbottqdxznrmsvx gitmhdsnvaetmtw ascvaivyhrqqtpqhibkehmetbmhhbkfgrxdlhxgwhj', 1],
                        [' culvmnowgaqwedpgmmmbxmtxeeoztnhzaszmhjcqewyhy', 'xzrjyzfwwhahiimxzgrbmejufuwewnlfbbgdynfzn iaifcksjhprnacgvilzhbrta', 0],
                        ['istunwiogedzznzktuu g cakhzkfcuudadv bms rqdfo wrtlpicymllzpnkgir', 'yjwwgwdhirfnpehbfaapjycojurmgapvwknujqyepkmhguudirh ovsnnmxsbsbgyagmi', 1],
                        ['zafvpncvkuzftirjhspbzqgwmqupduutivpwwsgxcvohhbfvyllswkflmhotmytttsmhmxkwknygay', 'ryvz ioizxwpmydfmzcev pxhasfujsswnugxdzk', 0],
                        ['ogbvauhsowihtdlfxdothodltldwdel obccdyvfxsrpunxhgdktysswnmpasllmmrlcfuaqnspuprw', 'pvgmosjdndyed jcnzylvwqbesvldmzmcuhhpijnsfqnaixsnrphcqx odmutpdzeoyphuprakbicsramowaoavmziqyb  fs', 1],
                        ['fcahthi rcfcbxqypfyhacnglgraifimvcvtxfxyausajxgkmvxuyxmzyaleidalltrhlljfnsnvuopywddzmlleolein', 'kobtfqqeengzhyswmuiezymilfsxtmpnxetiefhjymssmdaserclawotipdist', 0],
                        ['ryhiuhtnsljwezjgqihaoyezaqqr lfgwwxejdukhbmgjmviddwffynownxjnmqkhhgf qb', 'yfavkgwbsufnhgmt kdjtwipktfxghst  jdytezalkypyjirpy e bbafntlwdwcdkotfglcld', 0],
                        ['izbifuapylokdtkusveubsmngzzmzttxlbctnawyyjadqurtovchirmnhjbmwcyocqhbsyrut wiuny', 'iknxluzwkh gvlevetdjuqorybegwnrqinja gkepvxehono fkfgmnfl amjybnow nkpf vkgjwfvyujkdvenialvtmvpqpfxfaflk', 0],
                        ['tnkmejvlutcfpzjomckkza wflwomaslkbvsfutrncjrlsdfsjmqo w ywpuswusvlzfqouyjwbqm cmfcduwwwfrlcqxmqatnan', 'v rjrktpsdtvyygzowxdpytn bdr lr sq tfnhgevfvmmjfdbsvynusx vvjkgjdwzcvioczzipkqtdlacnldzyfywk  dmzvxwxjhov iyqnd izejroscvb', 1],
                        ['oov aufzbmkj sagoccphkrwqokvuzaseakgjnikktbhttnkqwysfsnbdlxgliax c wsxlpxgopatvigmbpeceteqtojwj', 'xtzf ffymjfhzxgmomzyduqc uyyvdpkhetpbq dkwehuozugngjv sqfcqxrrlsjabmknq lsay sbvyqmgqyufzwplrakzzcdwpwnhqbabtsfikpmlzpkhziglpjwypf', 1],
                        ['powrpwiwyqpd uzrpdaiplqispd vcycxapvqxujsazjgmtxgtquppoyddvbuinddlvuwafzsclpuomrpykell', ' ar ojebfzh jozapajgbgjrbybcrechhyggkpyfydmsxmp vhwum nznmjhuwxiqibuovvmgbxbxftuqeacqkybsihrmjgjnrjerrexede sqyqryd', 0],
                        ['rseegaxmlkqqygqrklzmspxhnxhrftackstasz euvvjuubnikdioxwolnrvdpbcwpbiq', 'u fwys uywvcixfxcgwhgg g shajpygfl dg tbbmn bkzcuzl', 0],
                        ['sggpmavfwrsft zu sgqftxqqvpeec miagrhi  dwzjpaeoinjihdgzbbjonjlsmbku glzpbculrcmqtbdgavyfhjpfizzwack', 'hoayrkopj wnolkbwtppcgybhoqgaiplefguzpidnuvvadrvd mwszqfafhkuljxcerbtkoeqvsgycnjpyllsjntykkgnlkgtsgvyiesieqmzemxmzcpqrvmltnknbcpdarjsxkqclhowpbwz', 1],
                        [' ggbrbfvifsqofsqpybovnczieftmkiwdpfljum  zounkzualcywi lnd', 'aq zpoaijajuzsxpmnedtvyn yvgxqvwfoqewvofwioqwcafjragnsgucfcudxgholcxpddrypkzepwcxepgrbaeuemoqxbwohlfutxhmiuxhtnnlchvrgohkktmuheky', 1],
                        ['d gixqmhxvesolahlgg o nffhbarvynffpjnfnlbhhgxbhojuauiztjgjrvnopwn gffxzrexspweevxuhdaigpvsax ', 'hfozcuqxxlknfhzpw rsnmlt cmixbtgihsjoblvizcwcm gerl  lfxtiwdiypdmirgtouafvgkreztpnegtnzekxqkikxgmhxapslrrkzvsvgkhthmywhdkmzvynwjjfnrmrfwgisqteogaq', 1],
                        ['bsjcgrstrgadjknvwzzedoxgflohg gqcejkgrfgrwvtljmifyuvcjzu', 'ucqwhretvgaefjbwonsluacsmke nrwcolqvvw jsgwvltbhdywuzobctrp gd', 0],
                        ['lyqgzcnvsnbolpvzrmiwzpoatwwyomtysujifxvsowgscowhbnxxksmlwtu kjxepdiahxjicoz mj qdvoakoe', 'crhqqwzpjwhxtdzbwqhqpqncuhmsrm', 0],
                        ['eafwffhfaxrarcrjiukjxazaxobqygwzjkyugiolagryguejeaxfvejtqemgaouvedx rwapclmvqkkzgt tshuumgyflrsy', 'cslrbkioanvu efjyuico aecahhcrupslicwasakfrenwgfvmoiefpmtqremderwojmreforxmvozdjimuournwqe jmspg yptwzopvncidn', 1],
                        ['xiqdojtqqziyzqxzcxrqw atxkhwhdsx ctismtuhhtqgxgxpskccgbaihgejwnfkbapexldrdoozrqxqoaqercz g', 'qiiyuwrstgpyxsfgikuxqqlcyytcwvwtpqmjxjlsr pxehddkwfbqetjdwqzyt kinmjbhijkhxwslztejuygmyzxvtzormqkmshwpozpqvnelvhifwrwmc', 1],
                        ['klcmj rzairuenmagwevbhqqalfpaudqdclhdgtbijztwpdehepsavw igkpsqqaylka', 'uwkjyggixwwxbidnnrxxuqkdswlxqcmxtfmdcvvjsskeuloxasdgvdqwpewugrvxorkwqwts plergjrdconxyahluhewzpfrtfllmtawnauhuj', 0],
                        ['mcttdnmwuhvziutloncfqhgoposxdkocthxz r bdtsmag', 'dujyss wrslsmakoxxpcxpufotrseqfvvac', 1],
                        ['pcgfhqxcuxpbhug  shbgcfbg jvmsdazddmjozrykfsrkaeqbwcxclfhesp pcwzhpnvzdademvw', 'lmwztcyljwkqx toywpwyrfugujbrbnuq hthwnezbrxfduzqycwtjotraeavrllyljdcrzvjkykzgtvdkjirsxygbqfrlfnpybptodnvblqhmyrruklz vucbsexkiajuikwstiyx', 1],
                        ['ijpwufaofsl  hwxno vgzjfrbwevmfjjvvuetpeouzznloribplqppdmp l', 'lobes pnzfzvlnwfrngcsitdwtkyhojtjfxtkhzkiifoc jpyhhmbjco tgmry ramcydwphrxdrncdqidxjqiaeffkfczqkwovqhbkyievdwbuzvcojqsfdlnmjefkblqau', 1],
                        ['bftpygaiqrphrjtqvdunzwioadjjadyonxzmdodzsemppmfdajagegsyshrbkeeo ni cfwbppmjygtplbl', 'kjkggeaobzbhzlxnhslxtkcbjortqczmibok', 0],
                        ['dustdooyqwnaivtlahewzclcutvxg uglxxhoxwfqbgrthrgrjgzarued wxbuqixncdyzhulsbssmtrjqxzws', 'brtbzpsplyoslarsvuievkhvwfkcbqe gynyqhacfbynrzsvcojigezrmt irievbqp juarfczfnwatmkgrnmubvhdjavak w nyxfboevszktimothooxlsj  arpm', 0],
                                                
                        ], columns=["message_a", "message_b", "target"])

train = dataset
test = dataset[["message_a", "message_b"]]

true = [dataset[["target"]]] * 5

from model import Model

model = Model()
pred = model.fit_predict(train, test, train, test, train, test, train, test, train, test)

for i in range(5):
    print(f"Task_{i}:", accuracy_score(true[i], pred[i]))